# Generated by Django 5.1.3 on 2024-12-15 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='recipes/'),
        ),
    ]
